hometask
MaxSkydan/Hillel_aqa_Max pull request #2
Opened 2023-12-08 13:29 UTC by MaxSkydan

2023-12-09 08:31 UTC, antohaUa requested changes
In general good solution - just require cosmetic fixes mentioned by me in comments

2023-12-09 08:31 UTC, antohaUa commented on hometask3.py
> +logging.basicConfig(level=logging.INFO, format='[%(asctime)s] %(levelname)s: %(message)s')
logger was not yet examined by us - but ok if you want  - better to use it in such way
```
_log = logging.getLogger('Main')

console_handler = logging.StreamHandler()
log_format = logging.Formatter('[%(asctime)s %(levelname)s]: %(message)s')
console_handler.setFormatter(log_format)
_log.addHandler(console_handler)
_log.setLevel(logging.DEBUG)

text = 'text'
_log.info(text)
```

2023-12-09 08:31 UTC, antohaUa commented on hometask3.py
> +# we have norway text in old style formatting
Task description better to place into module docstring at the top.

2023-12-09 08:31 UTC, antohaUa commented on hometask3.py
> +norway_text = 'Automatisering akselererer %syeblikket da roboter vil erobre planeten v%sr. (%s)' % ('ø', 'å', 'Æ')
Here and below linter gives us smth aka `E501 line too long (114 > 79 characters)` - you need to fix it

2023-12-09 09:31 UTC, MaxSkydan commented
fixed

2023-12-13 17:04 UTC, antohaUa approved these changes
Good

2023-12-13 17:04 UTC, antohaUa commented on hometask3.py
> +# re-write the same text as:
comment characters better to remove - cause text inside docstring

2023-12-13 18:53 UTC, merged